-- 코드를 작성해주세요
SELECT COUNT(I.FISH_TYPE) AS "FISH_COUNT", F.FISH_NAME AS "FISH_NAME"
FROM FISH_NAME_INFO AS F
JOIN FISH_INFO AS I ON I.FISH_TYPE = F.FISH_TYPE
GROUP BY I.FISH_TYPE, F.FISH_NAME
ORDER BY COUNT(I.FISH_TYPE) DESC